name: 'Gitscaffold – Roadmap to GitHub Issues'
description: 'Convert a roadmap file to GitHub issues using scaffold CLI'
inputs:
  roadmap-file:
    description: 'Path to the roadmap file (YAML/JSON)'
    required: false
    default: 'roadmap.yml'
  repo:
    description: 'GitHub repository (owner/repo)'
    required: true
  github-token:
    description: 'GitHub token (use ${{ secrets.GITHUB_TOKEN }})'
    required: false
    default: '${{ secrets.GITHUB_TOKEN }}'
  dry-run:
    description: 'Validate without creating issues'
    required: false
    default: 'false'
runs:
  using: 'docker'
  image: 'Dockerfile'
branding:
  icon: 'map'
  color: 'blue'
