name: 'Gitscaffold – Roadmap to GitHub Issues'
description: 'Convert a roadmap file to GitHub issues using gitscaffold CLI'
inputs:
  roadmap-file:
    description: 'Path to the roadmap file (YAML/JSON)'
    required: false
    default: 'roadmap.yml'
  repo:
    description: 'GitHub repository (owner/repo)'
    required: true
  github-token:
    description: 'GitHub token (use ${{ secrets.PERSONAL_TOKEN }})'
    required: false
    default: '${{ secrets.PERSONAL_TOKEN }}'
  dry-run:
    description: 'Validate without creating issues'
    required: false
    default: 'false'
  openai-key:
    description: 'OpenAI API key (use ${{ secrets.OPENAI_API_KEY }})'
    required: false
    default: ''
  apply:
    description: 'Apply enriched bodies to created issues (for markdown imports)'
    required: false
    default: 'false'
runs:
  using: 'docker'
  image: 'Dockerfile'
branding:
  icon: 'map'
  color: 'blue'