name: Publish Python package

on:
  push:
    tags:
      - 'v*.*.*'
  # Allow manual dispatch via GitHub UI or CLI
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - name: Install build tools
        run: pip install --upgrade build twine
      - name: Build distribution
        run: python -m build --sdist --wheel
      - name: Verify version
        run: |
          PACKAGE_VERSION=$(python -c 'from scaffold import __version__; print(__version__)')
          if [ "v$PACKAGE_VERSION" != "${{ github.ref_name }}" ]; then
            echo "Version in __init__.py (v$PACKAGE_VERSION) does not match tag (${{ github.ref_name }})"
            exit 1
          fi
      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@v1.5.1
        with:
          password: ${{ secrets.PYPI_API_TOKEN }}
