name: Release

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install build tools
        run: pip install --upgrade build twine

      - name: Build distribution
        run: python -m build

      - name: Publish to PyPI
        if: ${{ !env.ACT }}
        uses: pypa/gh-action-pypi-publish@v1.5.0
        with:
          password: ${{ secrets.PYPI_API_TOKEN }}

      - name: Extract release notes
        id: extract_release_notes
        run: |
          # Extracts content for the release note. It looks for a heading with the git tag,
          # and captures everything until the next heading.
          # GITHUB_REF_NAME is the tag that triggered the workflow (e.g. v1.2.3)
          awk '/^## / {if(p) exit; if($2 == "${{ github.ref_name }}") p=1; next} p' docs/release.md > release_notes.md

      - name: Create GitHub Release
        if: ${{ !env.ACT }}
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.ref_name }}
          name: ${{ github.ref_name }}
          body_path: release_notes.md
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
