name: Publish & Notify Release

on:
  push:
    tags:
      - 'v*.*.*'
  workflow_dispatch:

jobs:
  publish:
    name: Build and Publish to PyPI
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - name: Install build tools
        run: pip install --upgrade build twine
      - name: Build distribution
        run: python -m build --sdist --wheel --no-isolation
      - name: Verify version matches tag
        run: |
          PACKAGE_VERSION=$(python -c 'from scaffold import __version__; print(__version__)')
          if [ "v$PACKAGE_VERSION" != "${{ github.ref_name }}" ]; then
            echo "Version in __init__.py (v$PACKAGE_VERSION) does not match tag (${{ github.ref_name }})"
            exit 1
          fi
      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@v1.5.1
        with:
          pypi_token: ${{ secrets.PYPI_TOKEN }}
          skip_existing: true

  notify:
    name: 🚀 Notify Release Triggered
    runs-on: ubuntu-latest
    needs: publish
    steps:
      - uses: peter-evans/create-or-update-comment@v2
        with:
          token: ${{ secrets.PERSONAL_TOKEN }}
          issue-number: 1
          body: |
            ### Release ${{ github.ref_name }} Initiated
            A new release tag ${{ github.ref_name }} has been pushed.
            • PyPI package publishing is handled by this workflow.
            • Check the Actions tab for its status.
