name: Release Package & Action

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  publish-action:
    name: 🚀 Notify Release Triggered
    runs-on: ubuntu-latest
    # This job no longer depends on a local PyPI publish,
    # as pypi-publish.yml handles the actual publishing.
    steps:
      - uses: peter-evans/create-or-update-comment@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          issue-number: 1 # Ensure this issue number is where you want notifications
          body: |
            ### Release ${{ github.ref_name }} Initiated
            A new release tag ${{ github.ref_name }} has been pushed.
            • PyPI package publishing is being handled by the 'Publish Python package' workflow.
            • Check the Actions tab for its status.
