name: Test and Update Coverage

on:
  push:
    branches:
      - main

jobs:
  test-and-update-coverage:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install .[test]
          pip install pytest-cov

      - name: Run tests and generate coverage report
        run: pytest --cov=scaffold --cov-report=term-missing > coverage.txt || echo "Tests failed, skipping coverage update."

      - name: Update README with coverage
        run: python scripts/update_coverage.py coverage.txt README.md

      - name: Commit and push if README.md changed
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add README.md
          if git diff --staged --quiet; then
            echo "No changes to commit."
          else
            git commit -m "docs: Update test coverage in README"
            git push
          fi
