name: Test and Update Coverage

on:


jobs:
  test-and-update-coverage:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    concurrency:
      group: coverage-${{ github.ref }}
      cancel-in-progress: true

    permissions:
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install .[test]

      - name: Run tests
        run: pytest || echo "Tests failed."
